---
title: "Homework 4"
author: "Camron Pearce"
date: "November 8, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, include = FALSE}

library(readr)
library(dplyr)
library(ggplot2)
library(lubridate)
library(tibble)
library(tidyr)
library(broom)
library(stringr)
library(purrr)
library(forcats)
library(scales)
```

## Tidying the Data
```{r importing data set, include = T, echo = FALSE, warning = FALSE}
homicides <- read.csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv") %>% 
  unite(city_name, city, state, sep = ", ", remove = T)
```
```{r, homicide analysis, include = TRUE, warning = FALSE}
total_homicides <- homicides %>% 
  group_by(city_name) %>% 
  count()
  
unsolved <- homicides %>% 
  select(city_name, disposition) %>% 
  mutate(not_solved = disposition %in% c("Closed without arrest",
                                         "Open/No arrest")) %>% 
  filter(not_solved == T) %>% 
  group_by(city_name) %>% 
  count() %>% 
  rename(total_unsolved = n) %>% 
  ungroup()

total_unsolved <- unsolved %>% 
  left_join(total_homicides, by = "city_name") %>% 
  rename(unsolved =  "total_unsolved",
         total_homicides = "n")

balt_homicides <- total_unsolved %>% 
  filter(city_name == "Baltimore, MD")
balt_homicides
```
## Statistical Analysis of Baltimore
```{r prop_test, include = T, echo = F}
prop.test(x = balt_homicides$unsolved,
          n = balt_homicides$total_homicides)
balt_test <- prop.test(x = balt_homicides$unsolved,
          n = balt_homicides$total_homicides)
tidy(balt_test)
```

## Statistical Testing for Unsolved Homicides by City

```{r, fig.width=4.5, fig.height=7}
unsolved_df <- total_unsolved %>% 
  mutate(newcol = map2(unsolved, total_homicides,
                       ~ prop.test(.x, n = .y) %>% 
                  {tibble(estimate = .[["estimate"]],
                         CI_lower = .[["conf.int"]][[1]], 
                         CI_upper = .[["conf.int"]][[2]])})) %>%
  unnest() %>% 
  mutate(city_name = factor(city_name, levels = city_name[order(estimate)]))
  

unsolved_df %>% 
  ggplot(aes(estimate, city_name)) +
  geom_point(color = "white")+
  geom_errorbarh(aes(xmin = CI_lower,
                            xmax = CI_upper, 
                             y = city_name, 
                             height = 0), color = "white") +
  theme_dark() +
  scale_x_continuous(labels = percent) +
  labs(x = "Percent of homicides that are unsolved",
       y = "") +
  ggtitle("Unsolved homicides by city",
          subtitle = "Bars show 95% confience interval")
   
```

